## Introduction to `astropy.coordinates`
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Danselem/brics_astro/blob/main/Week4/02_astropy_coordinates.ipynb)


Now that we have a solid understanding of `astropy.units` and how to represent physical quantities with consistent, meaningful units, we can move forward to a central topic in astronomical computing: **celestial coordinate systems**.

The `astropy.coordinates` subpackage provides a powerful and flexible framework for representing and transforming astronomical positions and motions. It allows astronomers to specify positions of objects in various coordinate systems, convert between them, and perform operations such as angular separations, projections, and velocity calculations.

This module is essential for tasks involving:
- Sky positions (e.g., RA/Dec, Galactic coordinates)
- Proper motions and radial velocities
- Coordinate transformations (e.g., ICRS ↔ Galactic ↔ AltAz)
- Observation planning and target tracking
- Parsing, formatting, and aligning catalogs

Behind the scenes, `astropy.coordinates` is fully integrated with `astropy.units`, so all angles, distances, and velocities are unit-aware, ensuring physical and computational consistency.

In this section, we will focus on the fundamental functionality of the `astropy.coordinates` module — the tools most commonly used to define, interpret, and convert astronomical positions. Mastering these basic elements will be essential for working with astronomical databases and sky catalogs later, particularly when using tools such as `astroquery`.


**Note**
If you are running this jupyter notebook from Colab, then run the next cell by pressing `SHIFT+ENTER` to install the required packages for this notebook. Otherwise, skip the next cell.

In [1]:
!pip install -q astropy

In [2]:
from astropy import units as u
from astropy.coordinates import SkyCoord
import numpy as np

coord = SkyCoord(ra=138.0108*u.degree, dec= -64.8625 *u.degree, frame='icrs') #NGC 2808
print(coord)
print(type(coord))

<SkyCoord (ICRS): (ra, dec) in deg
    (138.0108, -64.8625)>
<class 'astropy.coordinates.sky_coordinate.SkyCoord'>


In this cell, we create an object of the `SkyCoord` class from the `astropy.coordinates` module to represent the sky position of the globular cluster **NGC 2808**.

We provide:
- **Right Ascension (RA)**: 138.0108 degrees  
- **Declination (Dec)**: −64.8625 degrees  
- **Coordinate frame**: `'icrs'` (International Celestial Reference System), the standard celestial frame based on extragalactic reference points

By explicitly attaching the unit `u.degree` to each value, we ensure unit consistency and enable the coordinate object to interact properly with other tools in the `astropy` ecosystem.

The resulting `SkyCoord` object encapsulates both position and reference frame information, and serves as the foundation for coordinate transformations, distance associations, proper motion handling, and querying astronomical databases using tools like `astroquery`.


In [3]:
#Warning: astropy.coordinates can digest any coordinate system — keep your fingers away from the input!
coord = SkyCoord(138.0108, -64.8625, frame='icrs', unit='deg')
print(coord)
coord = SkyCoord('09h12m2.6s', '-64d51m45s', frame='icrs')
print(coord)
coord = SkyCoord('09 12 2.6 -64 51 45', unit=(u.hourangle, u.deg))
print(coord)
coord = SkyCoord('09:12:2.6 -64:51:45', unit=(u.hourangle, u.deg))
print(coord)

<SkyCoord (ICRS): (ra, dec) in deg
    (138.0108, -64.8625)>
<SkyCoord (ICRS): (ra, dec) in deg
    (138.01083333, -64.8625)>
<SkyCoord (ICRS): (ra, dec) in deg
    (138.01083333, -64.8625)>
<SkyCoord (ICRS): (ra, dec) in deg
    (138.01083333, -64.8625)>


In [4]:
print(coord.ra,coord.dec)
print(type(coord.ra))
print(type(coord.dec))

138d00m39s -64d51m45s
<class 'astropy.coordinates.angles.core.Longitude'>
<class 'astropy.coordinates.angles.core.Latitude'>


In this cell, we retrieve the stored **Right Ascension** and **Declination** from the `SkyCoord` object using the `.ra` and `.dec` attributes.

These attributes return `Quantity` objects from `astropy.units`, which means they retain both the numerical value and the unit (in this case, degrees). This allows for safe arithmetic, conversion to other units, and precise control over formatting.

By printing `type(coord.ra)`, we confirm that the output is not just a number but an instance of `astropy.units.Quantity`. This reinforces the fact that `SkyCoord` maintains full unit awareness internally.


In [5]:
print(coord.ra.hour,coord.dec.deg)
print(type(coord.ra.hour))


9.200722222222224 -64.8625
<class 'numpy.float64'>


In this cell, we extract the **Right Ascension** and **Declination** from the `SkyCoord` object, but in alternative representations:

- `.ra.hour` converts the right ascension from degrees to **hours**, since RA is traditionally measured in hours, minutes, and seconds in astronomy (1 hour = 15 degrees).
- `.dec.deg` simply returns the declination in decimal degrees, which is the default angular unit for declination.

Note that `.ra.hour` returns a plain Python float — it strips away the unit metadata and gives only the numerical value in hours. This can be useful for certain formatting or external tools, but lacks the unit safety of `Quantity` objects.

By printing `type(coord.ra.hour)`, we verify that the result is no longer a `Quantity` but a standard `float`.


In [6]:
print(coord.ra.hms)
print(coord.dec.dms)

hms_tuple(h=np.float64(9.0), m=np.float64(12.0), s=np.float64(2.600000000004883))
dms_tuple(d=np.float64(-64.0), m=np.float64(-51.0), s=np.float64(-44.99999999998977))


In this cell, we access the `.ra.hms` attribute of the `SkyCoord` object.

The `.hms` property returns the **hours**, **minutes**, and **seconds** representation of the Right Ascension (RA) as a named tuple:  
`hms = (hour, minute, second)`

This format is especially useful in astronomical catalogs, telescope pointing systems, and human-readable reports where RA is traditionally expressed in sexagesimal units.

Unlike `.ra.hour`, which returns a single float in hours, `.ra.hms` provides a full breakdown for easy formatting or display:

- `coord.ra.hms.h`: hours  
- `coord.ra.hms.m`: minutes  
- `coord.ra.hms.s`: seconds

The resulting values are pure floats, not `Quantity` objects, so units are implied by context rather than enforced.


In [7]:
print(coord.ra.radian,coord.dec.radian)

2.4087434450878074 -1.132064186074822


In this cell, we access the `.radian` attribute of the Right Ascension and Declination stored in the `SkyCoord` object.

- `.ra.radian` returns the Right Ascension in **radians**
- `.dec.radian` returns the Declination in **radians**

Both values are returned as standard Python floats (not `Quantity` objects), and the unit is implicitly understood to be **radians**.

This representation is useful when working with trigonometric functions from libraries like NumPy or SciPy, which expect input angles in radians. However, because units are no longer attached, it's important to track units manually and avoid unit mismatches.


In [8]:
print(coord.to_string('decimal'))
print(coord.to_string('dms'))
print(coord.to_string('hmsdms'))

138.011 -64.8625
138d00m39s -64d51m45s
09h12m02.6s -64d51m45s


In this cell, we use the `.to_string()` method of the `SkyCoord` object to display the coordinates in various string formats.

The method formats the Right Ascension and Declination into human-readable strings using different notations:

- `coord.to_string('decimal')`  
  Returns RA and Dec as decimal degrees, separated by a space.  
  Example: `'138.0108 -64.8625'`

- `coord.to_string('dms')`  
  Returns both RA and Dec in **degrees:minutes:seconds (DMS)** format.  
  Example: `'138d00m38.88s -64d51m45s'`  
  This is useful when reporting coordinates in formats commonly used in catalogs or observational logs.

- `coord.to_string('hmsdms')`  
  Formats RA in **hours:minutes:seconds (HMS)** and Dec in **DMS**.  
  Example: `'09h12m2.60s -64d51m45s'`  
  This is the traditional astronomical format for sky coordinates.

These formatting options are especially useful when exporting results, generating catalogs, or matching coordinate formats from external datasets.


In [ ]:
print(coord.galactic)

<SkyCoord (Galactic): (l, b) in deg
    (282.19166541, -11.25257989)>


In this cell, we access the `.galactic` attribute of the `SkyCoord` object to obtain the position of the same object (NGC 2808) in the **Galactic coordinate system**.

The `.galactic` attribute returns a new `SkyCoord` object representing the same physical location on the sky, but in terms of:

- **Galactic Longitude (`l`)** — measured in degrees, increasing in the direction of the Galactic rotation
- **Galactic Latitude (`b`)** — measured in degrees, positive above the Galactic plane

This transformation is handled internally by `astropy`, using the built-in coordinate transformation graph. The result remains a fully unit-aware `SkyCoord` object and can be further queried, transformed, or formatted like any other coordinate.

Galactic coordinates are especially useful when studying the structure and components of the Milky Way.


In [ ]:
NGC_2808 = SkyCoord.from_name("NGC 2808")
print(NGC_2808)

<SkyCoord (ICRS): (ra, dec) in deg
    (138.01291667, -64.8635)>


In this cell, we use `SkyCoord.from_name()` to automatically retrieve the celestial coordinates of **NGC 2808** by querying the **SIMBAD** astronomical database.

This method sends a network request and resolves the name `"NGC 2808"` to its ICRS (RA/Dec) coordinates. The returned result is a standard `SkyCoord` object, ready for further use.

This feature is especially helpful when working with named astronomical objects, saving time and reducing errors compared to manually entering coordinates.

> **Pro tip**: Even if you're banned from Google or can't load Wikipedia, you can still resolve star cluster positions like a pro! Thanks to `astropy` and SIMBAD!


In [ ]:
ra_deg = np.array([6.023625, 13.18875, 78.528625, 81.046667, 138.0108,
                   201.6975, 229.63875, 250.4225, 265.175833, 322.493958])
dec_deg = np.array([-72.081283, -26.582806, -40.046875, -24.524139, -64.8625,
                    -47.479722, 2.081, 36.460278, -53.674694, 12.16625])

cluster_names = np.array([
    "NGC 104",    # 47 Tucanae
    "NGC 288",
    "NGC 1851",
    "NGC 1904",   # M79
    "NGC 2808",
    "NGC 5139",   # Omega Centauri
    "NGC 5904",   # M5
    "NGC 6205",   # M13
    "NGC 6397",
    "NGC 7078"    # M15
])

dist_kpc = np.array([
    4.5, 8.9, 12.1, 12.9, 9.6,
    5.2, 7.5, 7.7, 2.3, 10.4
])  #GAIA/DR3 distances

cluster_coords = SkyCoord(ra=ra_deg * u.deg, dec=dec_deg * u.deg, distance = dist_kpc*u.kpc, frame='icrs') # Create a SkyCoord array from NumPy arrays
print(cluster_coords) #RA and Dec in degrees for 10 globular clusters (J2000)

<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, kpc)
    [(  6.023625, -72.081283,  4.5), ( 13.18875 , -26.582806,  8.9),
     ( 78.528625, -40.046875, 12.1), ( 81.046667, -24.524139, 12.9),
     (138.0108  , -64.8625  ,  9.6), (201.6975  , -47.479722,  5.2),
     (229.63875 ,   2.081   ,  7.5), (250.4225  ,  36.460278,  7.7),
     (265.175833, -53.674694,  2.3), (322.493958,  12.16625 , 10.4)]>


### Using NumPy Arrays with `SkyCoord`

In this cell, we demonstrate how to create a `SkyCoord` object using **NumPy arrays** for multiple celestial objects.

We define:
- An array of **Right Ascension** (`ra_deg`) values in degrees  
- An array of **Declination** (`dec_deg`) values in degrees  
- An array of **distances** (`dist_kpc`) in kiloparsecs  
- A list of **names** for 10 well-known globular clusters

By passing these arrays directly into the `SkyCoord` constructor along with their appropriate units, we create a structured collection of coordinates. Each element includes full 3D spatial information: angular position (RA, Dec) and distance.

This approach allows efficient, vectorized operations on many coordinates at once and is ideal for working with astronomical catalogs and large datasets.


In [ ]:
sep_3d = cluster_coords[0].separation_3d(cluster_coords[9])
sep_ang = cluster_coords[0].separation(cluster_coords[9])
print(f"3D distance between {cluster_names[0]} and {cluster_names[9]}: {sep_3d.to(u.kpc):.2f}")
print(f"Angular separation {cluster_names[0]} and {cluster_names[9]}: {sep_ang.to(u.degree):.2f}")

3D distance between NGC 104 and NGC 7078: 11.26 kpc
Angular separation NGC 104 and NGC 7078: 89.00 deg


### Measuring 3D Distance Between Two Globular Clusters

In this cell, we compute the **true spatial separation** between two globular clusters using their full 3D coordinates.

Specifically, we call:

```python
cluster_coords[0].separation_3d(cluster_coords[9])
```

This computes the **Euclidean distance in 3D space** between the first cluster (`NGC 104`) and the last cluster (`NGC 7078`) in our list.

Unlike angular separation (which only considers position on the sky), `.separation_3d()` uses both:
- Angular coordinates (RA, Dec)
- Radial distances (in kiloparsecs)

The result is returned as a `Quantity` with physical units (e.g., `kpc`), giving the **true line-of-sight separation** between the two objects in three-dimensional space.


### Working with Angles in `astropy.coordinates`

In astronomy, angles are everywhere — from sky coordinates (RA/Dec, Alt/Az) to angular separations, field of view, proper motions, and more. To handle such angular quantities with both **unit safety** and **astronomical precision**, `astropy.coordinates` provides the `Angle` class.

The `Angle` object is a specialized form of `Quantity` designed specifically for angular values. It allows:

- Flexible creation from degrees, radians, hours, DMS, or HMS strings
- Easy conversion between angular formats
- Safe arithmetic (addition, subtraction, wrapping)
- High-precision comparison and transformations
- Use of custom wrapping and normalization (e.g. `wrap_at(180*u.deg)`)

Because `Angle` is fully unit-aware and interoperable with `SkyCoord`, it's ideal for precise and readable angular computations — whether you're rotating frames, computing angular distances, or converting between coordinate systems.

In short, the `Angle` class gives you both the **power of astropy.units** and the **expressiveness of astronomical angular conventions**, all in one object.


In [ ]:
from astropy.coordinates import Angle
Angle('10.2345d')              # String with 'd' abbreviation for degrees
Angle(['10.2345d', '-20d'])    # Array of strings
Angle('1:2:30.43 degrees')     # Sexagesimal degrees
Angle('1 2 0 hours')           # Sexagesimal hours
Angle(np.arange(1., 8.), unit=u.deg)  # Numpy array from 1..7 in degrees
Angle('1°2′3″')               # Unicode degree, arcmin and arcsec symbols
Angle('1°2′3″N')               # Unicode degree, arcmin, arcsec symbols and direction
Angle('1d2m3.4s')              # Degree, arcmin, arcsec.
Angle('1d2m3.4sS')              # Degree, arcmin, arcsec, direction.
Angle('-1h2m3s')               # Hour, minute, second
Angle('-1h2m3sW')               # Hour, minute, second, direction
Angle(10.2345 * u.deg)         # From a Quantity object in degrees
Angle(Angle(10.2345 * u.deg))  # From another Angle object

<Angle 10.2345 deg>

In [ ]:
a1 = Angle("10d30m")
a2 = Angle("2d15m")
a3 = a1 + a2
a4 = a1 - a2
print(f"Sum: {a3}")
print(f"Difference: {a4}")

Sum: 12.75 deg
Difference: 8.25 deg


### Angle Arithmetic

`Angle` objects support standard arithmetic:
- Addition and subtraction
- Multiplication/division by scalars
- Array operations

This is especially useful when calculating angular distances or adjusting positions.


# Summary: Core Concepts of `astropy.coordinates`

In this lesson, we explored the fundamental capabilities of the `astropy.coordinates` subpackage:

- Creation of coordinate objects using `SkyCoord` with scalar and array inputs
- Representation and formatting of celestial coordinates in degrees, radians, hms/dms
- Transformations between coordinate systems (e.g., ICRS, Galactic)
- Extraction of coordinate attributes (`ra`, `dec`, `galactic`, `.radian`, `.hms`, etc.)
- Name-based lookups using `SkyCoord.from_name()`
- Angular and 3D spatial separation calculations
- Vectorized coordinate handling using NumPy arrays

---

## Additional Topics Worth Exploring

We have only touched the surface of what `astropy.coordinates` can do. The following topics are highly recommended for further study:

### Coordinate Systems and Frame Transformations
- Full transformation graph between supported frames
- Custom frames and intermediate transformations  
[Docs: Transforming Coordinates](https://docs.astropy.org/en/stable/coordinates/transforming.html)

### AltAz and Observational Coordinates
- Working with `AltAz` frame for ground-based observations
- Using `EarthLocation` and `Time` for observer-specific calculations  
[Docs: AltAz Coordinates](https://docs.astropy.org/en/stable/coordinates/altaz.html)

### EarthLocation and Time-Aware Coordinates
- Creating observer locations with `EarthLocation`
- Combining with `Time` for precision observation planning  
[Docs: EarthLocation](https://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html)

### Proper Motions and Radial Velocities
- Representing space motion using `proper_motion` and `radial_velocity`
- Time propagation of position and velocity  
[Docs: Motions](https://docs.astropy.org/en/stable/coordinates/motion.html)

### Angle Utilities
- Use of `Angle`, `Latitude`, and `Longitude` classes
- Trigonometric operations, formatting, wrapping  
[Docs: Angle Classes](https://docs.astropy.org/en/stable/api/astropy.coordinates.Angle.html)

---

## Recommendations

- Use `SkyCoord` for all celestial position representations.
- Always use physical units with `astropy.units` for clarity and safety.
- Leverage vectorization with NumPy for working with large coordinate sets.
- Understand when and how to use coordinate transformations.
- Explore observational frames (`AltAz`, `Geocentric`, `Heliocentric`) for real-world scenarios.

For the full documentation, see:  
[https://docs.astropy.org/en/stable/coordinates/index.html](https://docs.astropy.org/en/stable/coordinates/index.html)
